services:
  # -----------------------------
  # PostgreSQL Database for Validator
  # -----------------------------
  postgres-validator:
    build:
      context: ..
      dockerfile: docker/db/Dockerfile
    image: postgres-validator:local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_ABCI_DB_USER: ${APP_ABCI_DB_USER}
      APP_ABCI_DB_PASSWORD: ${APP_ABCI_DB_PASSWORD}
      APP_ABCI_DB_SCHEMA: ${APP_ABCI_DB_SCHEMA}
      APP_EVM_DB_USER: ${APP_EVM_DB_USER}
      APP_EVM_DB_PASSWORD: ${APP_EVM_DB_PASSWORD}
      APP_EVM_DB_SCHEMA: ${APP_EVM_DB_SCHEMA}
    volumes:
      - postgres_validator_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "/postgresql/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  # -----------------------------
  # MPT DB (Node.js) for Validator
  # -----------------------------
  mpt-db-validator:
    build:
      context: ..
      dockerfile: docker/mpt/Dockerfile
    volumes:
      - mpt_validator_data:/app/data
    healthcheck:
      test: [ "CMD", "node", "/app/healthcheck.js" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  # -----------------------------
  # ABCI App (Quarkus) for Validator
  # -----------------------------
  app-abci-validator:
    build:
      context: ..
      dockerfile: docker/abci/Dockerfile
    environment:
      QUARKUS_PROFILE: prod
      APP_ABCI_DB_USER: ${APP_ABCI_DB_USER}
      APP_ABCI_DB_PASSWORD: ${APP_ABCI_DB_PASSWORD}
      APP_ABCI_DB_SCHEMA: ${APP_ABCI_DB_SCHEMA}
      POSTGRESSQL_DB_HOST: postgres-validator
      TENDERMINT_HOST: validator-node
      MPT_DB_HOST: mpt-db-validator
      CHAIN_ID: ${CHAIN_ID}
      COIN_SYMBOLE: ${COIN_SYMBOLE}
    depends_on:
      mpt-db-validator:
        condition: service_healthy
      postgres-validator:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/app/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  # -----------------------------
  # Validator Node (Tendermint)
  # -----------------------------
  validator-node:
    build:
      context: ..
      dockerfile: docker/validator/Dockerfile
    command: start --proxy_app tcp://app-abci-validator:26658
    volumes:
      - tendermint_validator_data:/tendermint/data
      - tendermint_validator_config:/tendermint/config
    depends_on:
      app-abci-validator:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

volumes:
  postgres_validator_data:
  mpt_validator_data:
  tendermint_validator_data:
  tendermint_validator_config:
