services:
  # -----------------------------
  # PostgreSQL Database for Validator
  # -----------------------------
  postgres-validator:
    image: postgres-validator:local
    volumes:
      - postgres_validator_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "/postgresql/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  # -----------------------------
  # MPT DB (Node.js) for Validator
  # -----------------------------
  mpt-db-validator:
    image: mpt-db-validator:local
    volumes:
      - mpt_validator_data:/app/data
    healthcheck:
      test: [ "CMD", "node", "/app/healthcheck.js" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  # -----------------------------
  # ABCI App (Quarkus) for Validator
  # -----------------------------
  app-abci-validator:
    image: app-abci-validator:local
    environment:
      QUARKUS_PROFILE: prod
    depends_on:
      mpt-db-validator:
        condition: service_healthy
      postgres-validator:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/app/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  # -----------------------------
  # Validator Node (Tendermint)
  # -----------------------------
  validator-node:
    image: validator:local
    command: start --proxy_app tcp://app-abci-validator:26658
    volumes:
      - tendermint_validator_data:/tendermint/data
      - tendermint_validator_config:/tendermint/config
    depends_on:
      app-abci-validator:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

volumes:
  postgres_validator_data:
  mpt_validator_data:
  tendermint_validator_data:
  tendermint_validator_config:
