services:

  # -----------------------------
  # MPT DB (Node.js)
  # -----------------------------
  postgresql:
    container_name: postgresql
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: graphene
      POSTGRES_PASSWORD: graphenepassword
      POSTGRES_DB: graphenedb
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U graphene" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      graphene-net:
        ipv4_address: 172.16.238.9

  # -----------------------------
  # MPT DB (Node.js)
  # -----------------------------
  mpt-db:
    container_name: mpt-db
    build:
      context: ..
      dockerfile: docker/db/Dockerfile
    volumes:
      - ./volumes/mpt/data:/app/data
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "node", "/app/healthcheck.js" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      graphene-net:
        ipv4_address: 172.16.238.10

  # -----------------------------
  # ABCI App (Quarkus)
  # -----------------------------
  app-abci:
    container_name: grph-abci
    build:
      context: ..
      dockerfile: grph-abci/src/main/docker/Dockerfile.legacy-jar
    image: quarkus/app-abci-jvm:local
    environment:
      QUARKUS_PROFILE: prod
    ports:
      - "3002:3002"
      - "26658:26658"
    extra_hosts:
      - "tendermint=172.16.238.13"
      - "mpt-db=172.16.238.10"
    depends_on:
      mpt-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/deployments/healthcheck.sh" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      graphene-net:
        ipv4_address: 172.16.238.11

  # -----------------------------
  # EVM App (Quarkus)
  # -----------------------------
  app-evm:
    container_name: grph-evm
    build:
      context: ..
      dockerfile: docker/Dockerfile.legacy-jar
    image: quarkus/app-evm-jvm:local
    extra_hosts:
      - "grph-abci=172.16.238.11"
      - "postgresql=172.16.238.9"
    environment:
      QUARKUS_PROFILE: prod
    ports:
      - "3003:3003"
    depends_on:
      app-abci:
        condition: service_healthy
      postgresql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/deployments/healthcheck.sh" ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      graphene-net:
        ipv4_address: 172.16.238.12

  # -----------------------------
  # Tendermint
  # -----------------------------
  tendermint:
    container_name: tendermint
    build:
      context: ..
      dockerfile: tendermint/Dockerfile
    image: graphene/tendermint:local
    command: start --proxy_app tcp://grph-abci:26658
    extra_hosts:
      - "grph-abci=172.16.238.11"
    volumes:
      - ./volumes/tendermint/config:/tendermint/config
      - ./volumes/tendermint/data:/tendermint/data
    depends_on:
      app-abci:
        condition: service_healthy
    ports:
      - "26656:26656"
      - "26657:26657"
    networks:
      graphene-net:
        ipv4_address: 172.16.238.13

networks:
  graphene-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
