name: sentry-${NODE_ENV}

services:
  # -----------------------------
  # PostgreSQL Database for Sentry
  # -----------------------------
  postgres-sentry:
    build:
      context: ..
      dockerfile: docker/db/Dockerfile
    image: postgres-sentry:local
    container_name: ${COMPOSE_PROJECT_NAME:-sentry}_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      APP_ABCI_DB_USER: ${APP_ABCI_DB_USER}
      APP_ABCI_DB_PASSWORD: ${APP_ABCI_DB_PASSWORD}
      APP_ABCI_DB_SCHEMA: ${APP_ABCI_DB_SCHEMA}
      APP_EVM_DB_USER: ${APP_EVM_DB_USER}
      APP_EVM_DB_PASSWORD: ${APP_EVM_DB_PASSWORD}
      APP_EVM_DB_SCHEMA: ${APP_EVM_DB_SCHEMA}
    volumes:
      - ../volumes/${NODE_ENV}/sentry/postgresql/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "/postgresql/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    networks:
      graphene-net:

  # -----------------------------
  # MPT DB (Node.js) for Sentry
  # -----------------------------
  mpt-db-sentry:
    build:
      context: ..
      dockerfile: docker/mpt/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-sentry}_mpt_db
    volumes:
      - ../volumes/${NODE_ENV}/sentry/mpt/data:/app/data
    healthcheck:
      test: [ "CMD", "node", "/app/healthcheck.js" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    networks:
      graphene-net:

  # -----------------------------
  # ABCI App (Quarkus) for Sentry
  # -----------------------------
  app-abci-sentry:
    build:
      context: ..
      dockerfile: docker/abci/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-sentry}_abci_app
    environment:
      QUARKUS_PROFILE: prod
      APP_ABCI_DB_USER: ${APP_ABCI_DB_USER}
      APP_ABCI_DB_PASSWORD: ${APP_ABCI_DB_PASSWORD}
      APP_ABCI_DB_SCHEMA: ${APP_ABCI_DB_SCHEMA}
      POSTGRESSQL_DB_HOST: postgres-sentry
      TENDERMINT_HOST: sentry-node
      MPT_DB_HOST: mpt-db-sentry
      CHAIN_ID: ${CHAIN_ID}
      COIN_SYMBOLE: ${COIN_SYMBOLE}
    depends_on:
      mpt-db-sentry:
        condition: service_healthy
      postgres-sentry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/app/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    networks:
      graphene-net:

  # -----------------------------
  # Sentry Node (Tendermint)
  # -----------------------------
  sentry-node:
    build:
      context: ..
      dockerfile: docker/validator/Dockerfile
    image: tendermint-sentry:local
    container_name: ${COMPOSE_PROJECT_NAME:-sentry}_tendermint
    environment:
      NODE_KEY_JSON: ${NODE_KEY_JSON}
      PRIV_VALIDATOR_KEY_JSON: ${PRIV_VALIDATOR_KEY_JSON}
      P2P_NODE_NAME: ${P2P_NODE_NAME}
      P2P_SEEDS: ${P2P_SEEDS}
      P2P_PERSISTENT_PEERS: ${P2P_PERSISTENT_PEERS}
      P2P_PRIVATE_PEER_IDS: ${P2P_PRIVATE_PEER_IDS}
      P2P_UNCONDITIONAL_PEERS: ${P2P_UNCONDITIONAL_PEERS}
    command: [
      "start",
      "--proxy_app", tcp://app-abci-sentry:26658,
      "--moniker", "${P2P_NODE_NAME}",
      "--p2p.pex",
      "--p2p.seed_mode",
#      "--p2p.seeds", "${P2P_SEEDS}",
      "--p2p.persistent_peers", "${P2P_PERSISTENT_PEERS}",
      "--p2p.private_peer_ids", "${P2P_PRIVATE_PEER_IDS}",
      "--p2p.unconditional_peer_ids", "${P2P_UNCONDITIONAL_PEERS}",
    ]
    volumes:
      - ../volumes/${NODE_ENV}/tendermint/sentry/data:/tendermint/data
      - ../config/tendermint/${NODE_ENV}/genesis.json:/tendermint/config/genesis.json
    depends_on:
      app-abci-sentry:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    networks:
      graphene-net:

  # -----------------------------
  # EVM App (Quarkus) for Sentry
  # -----------------------------
  app-evm-sentry:
    build:
      context: ..
      dockerfile: docker/evm/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-sentry}_evm_app
    environment:
      QUARKUS_PROFILE: prod
      APP_EVM_DB_USER: ${APP_EVM_DB_USER}
      APP_EVM_DB_PASSWORD: ${APP_EVM_DB_PASSWORD}
      APP_EVM_DB_SCHEMA: ${APP_EVM_DB_SCHEMA}
      APP_ABCI_HOST: app-abci-sentry
      POSTGRESSQL_DB_HOST: postgres-sentry
      TENDERMINT_HOST: sentry-node
      MPT_DB_HOST: mpt-db-sentry
      CHAIN_ID: ${CHAIN_ID}
      COIN_SYMBOLE: ${COIN_SYMBOLE}
    ports:
      - "3003:3003"
    depends_on:
      postgres-sentry:
        condition: service_healthy
      app-abci-sentry:
        condition: service_healthy
      sentry-node:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/app/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    networks:
      graphene-net:

  # -----------------------------
  # Graphene Explorer App
  # -----------------------------
  graphene-explorer-sentry:
    build:
      context: ..
      dockerfile: docker/explorer/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-sentry}_graphene_explorer
    ports:
      - "8080:8080"
    depends_on:
      app-evm-sentry:
        condition: service_healthy
      sentry-node:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "/app/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    networks:
      graphene-net:

networks:
  graphene-net:
    external: true