#!/bin/sh
set -e

echo "Creating application users and schemas..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- User 1
    CREATE USER ${APP_ABCI_DB_USER} WITH PASSWORD '${APP_ABCI_DB_PASSWORD}';
    CREATE SCHEMA IF NOT EXISTS ${APP_ABCI_DB_SCHEMA} AUTHORIZATION ${APP_ABCI_DB_USER};
    GRANT ALL PRIVILEGES ON SCHEMA ${APP_ABCI_DB_SCHEMA} TO ${ABCI_USER};

    -- User 2
    CREATE USER ${APP_EVM_DB_USER} WITH PASSWORD '${APP_EVM_DB_PASSWORD}';
    CREATE SCHEMA IF NOT EXISTS ${APP_EVM_DB_SCHEMA} AUTHORIZATION ${APP_EVM_DB_USER};
    GRANT ALL PRIVILEGES ON SCHEMA ${APP_EVM_DB_SCHEMA} TO ${EVM_USER};
EOSQL

echo "Application users and schemas created."
